spring.application.name=backend

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/prueba
spring.datasource.username=postgres
spring.datasource.password=0818
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
# CLI Configuration
# Set to true to enable CLI mode by default, or pass --cli argument on startup
app.cli.enabled=true
